### ISSUE TITLE
Lösung für Basket ID für AV-Daten, PLZ-Daten und GB-Kreise erarbeiten

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#10]
Die Idee "Zuerst Baskets anlegen, falls sie noch nicht existieren" ist grundsätzlich gut und würde ich so umsetzen. Wofür ich aber noch keine Lösung sehe: Dem Db2Db-Task müsste man als Parameter die Basket-IDs der soeben angelegten oder bereits existierenden Baskets mitgeben. An diese IDs gelangt man aber nur über einen SqlExecutor-Task, der SQL auf der Ziel-DB ausführt, denn der Db2Db-Task führt sein SQL ja auf der Quell-DB aus, wo er nicht an die Ziel-Basket-IDs herankommt. Also müsste man an den Resultatwert des SqlExecutors herankommen und ihn in einer "Gradle-Variablen" speichern, was, soviel ich weiss, nicht geht, weil der Task nichts in dieser Art zurückgibt.

Mein Vorschlag ist deshalb, eben doch doch fixe Basket IDs für die AV etc. zu definieren. Und entweder beim Anlegen des Schemas `--idSeqMin 100` oder so zu verwenden. Oder dann `--idSeqMin` nicht zu setzen und stattdessen Basket IDs im negativen Bereich zu verwenden.

**Comment by schmandr** [comment]
Eine Variante, um an die Ziel-Basket-IDs heranzukommen, wäre noch, mit einem _Exec_-Step `psql ...` auszuführen und vielleicht so ans Resultat zu kommen. Doku siehe https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html. Ist aber nicht besonders elegant, da es auf den externen Befehl _psql_ angewiesen ist.

**Comment by edigonzales** [comment]
Stand?

**Comment by schmandr** [comment]
Ich glaube, dass @edigonzales und @schmandr zu folgendem Schluss gekommen sind:

> Vorläufig auf der Variante mit negativen Basket-IDs belassen. Allenfalls später auf Variante mit `--idSeqMin` umstellen.

D.h. aus meiner Sicht belassen wir es eben vorläufig so und können den Issue schliessen, falls du auch einverstanden bist.

**Comment by andreasneumann** [comment]
Ok - schliessen wir das. Wir können das später immer noch verbessern, falls wir das Bedürfnis haben.
