### ISSUE TITLE
Grundwasserschutzzone 

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#101]
Aussage soll heissen:
- "Grundwasserschutzzone S1"
- "Grundwasserschutzzone S2"
- "Grundwasserschutzzone S3"

und bei Grundwasserschutzareale
- "Grundwasserschutzareale"

**Comment by Luescher** [comment]
i.O.

**Comment by Luescher** [comment]
Ach nein .... "Grundwasserschutzareale" muss "Grundwasserschutzareal" heissen ohne "e". Sorry. Kannst du das noch korrigieren.

**Comment by barpasen** [comment]
Soll das überall ersetzt werden, auch bei artcodeliste?
     SELECT
         DISTINCT ON (gwsareal.t_id)
         ....
         'Grundwasserschutzareale' AS aussage_de,
         'Grundwasserschutzareale' AS thema,
         gwsareal.typ AS artcode,
         'urn:fdc:ilismeta.interlis.ch:2017:Typ_Kanton_Grundwasserschutzareale' AS artcodeliste,

**Comment by Luescher** [comment]
Nur bei "aussage_de" soll "Grundwasserschutzareal" ohne "e" stehen

**Comment by barpasen** [comment]
Pull Request gemacht, Andi muss mergn
