### ISSUE TITLE
oereb_nutzungsplanung Job Gesetze anpassen

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#103]
* Bei ch.so.Baulinien muss Verlinkung zu "ch.admin.bk.sr.700" entfernt werden
* Bei ch.SO.Laermempfindlichkeitsstufen muss Verlinkung zu "ch.admin.bk.sr.700" entfernt werden und dafür die Verlinkung zu "ch.admin.bk.sr.814.41" muss ergänzt werden.
* Bei ch.SO.Waldabstandslinien muss Verlinkung zu "ch.admin.bk.sr.700" entfernt werden und dafür Verlinkung zu ch.admin.bk.sr.921.0 muss ergänzt werden

**Comment by edigonzales** [comment]
Test mit Baulinien: Verdoppelung der Rechtsvorschriften. Relativ viel SQL nötig, weil man auch noch die Multilingual-URIs flicken muss und ggf. unnötige Dokumente löschen muss (solche, die NUR mit Baulinien verknüpft sind, darf es ja nur einmal geben). Käsig die ganze Sache...

Läuft auf geo-t durch. Branch https://github.com/sogis/oereb-gretljobs/tree/npl-gesetze

![Screenshot 2020-04-10 at 19 05 55](https://user-images.githubusercontent.com/2767800/79008749-5b78b100-7b5e-11ea-92d4-37756dcae35f.png)
![Screenshot 2020-04-10 at 19 06 03](https://user-images.githubusercontent.com/2767800/79008759-5f0c3800-7b5e-11ea-9e8e-330cfce1791d.png)

**Comment by edigonzales** [comment]
Waldabstandslinien:

![Screenshot 2020-04-10 at 19 43 49](https://user-images.githubusercontent.com/2767800/79011120-a648f780-7b63-11ea-96fd-233f298f923c.png)
![Screenshot 2020-04-10 at 19 43 54](https://user-images.githubusercontent.com/2767800/79011127-aa751500-7b63-11ea-814c-a4929e3113a8.png)

**Comment by edigonzales** [comment]
Lärm:

![Screenshot 2020-04-10 at 20 27 53](https://user-images.githubusercontent.com/2767800/79013812-ce3b5980-7b69-11ea-9f9a-30ab6b22603a.png)

**Comment by edigonzales** [comment]
Ich finde es immer noch ziemlich doof bis eigentlich falsch, aber nun ja.

merged: https://github.com/sogis/oereb-gretljobs/pull/104

@Luescher Bitte gut testen.

**Comment by edigonzales** [comment]
Ok, das ist jetzt komisch. Der Kanton Zürich hat das Thema "Baulinien (kantonal/kommunal)".  Bei den gesetzlichen Grundlagen wird das RPG aufgeführt.

[Oereb-Auszug_261_HO4116_2020-04-11.pdf](https://github.com/sogis/oereb-gretljobs/files/4464344/Oereb-Auszug_261_HO4116_2020-04-11.pdf)

Bisschen willkürlich das Ganze.

**Comment by edigonzales** [comment]
Bei den Waldabstandslinien verweist der Kanton Zürich auf das Waldgesetz und das RPG. Bei den Lärmempfindlichkeitsstufen auf die LSV und das RPG. Das zeigt m.E. wirklich das die Verknüpferei mit den Gesetzen so nicht funktionieren kann. Ich denke das es (modell-)technisch problematisch ist und nur mit dieser doofen Verdoppelung machbar ist.

[Oereb-Auszug_261_OB4332_2020-04-11.pdf](https://github.com/sogis/oereb-gretljobs/files/4464363/Oereb-Auszug_261_OB4332_2020-04-11.pdf)

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/oereb-gretljobs/commit/30cb35cfa5a5167a7c760ff532ad1d9982b46103
