### ISSUE TITLE
oereb_waldgrenzen Typ ohne Geometrie nicht ins Rahmenmodell umbauen

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#109]
Der GRETL-Job läuft nicht durch https://gretl-i.so.ch/blue/organizations/jenkins/oereb_waldgrenzen/detail/oereb_waldgrenzen/14/pipeline.

Ich vermute es liegt daran, dass es Objekte unter awjf_statische_waldgrenze"."geobasisdaten_typ geben kann, die keine Geometrie (resp. kein zugehöriges Objekt in Tabelle "geobasisdaten_waldgrenze_linie") haben. Kannst du den Umbau so anpassen, dass nur "geobasisdaten_typ" mit einer Beziehung zu mindestens einer "geobasisdaten_waldgrenze_linie" hat ins Rahmenmodell importiert werden. Auch Dokumente die zu dem Typ ohne Geometrie liegen sollen nicht im ÖREB-Rahmenmodell erscheinen.

Die Erfassung durch AWJF ist so korrekt, es gibt Typen ohne Geometrien... so genannte negative Waldfeststellung. Da gibt es ein Dokument wo steht, es gibt keine Waldfeststellung in der Gemeinde.

**Comment by schmandr** [comment]
Gelöst mit #110  durch @barpasen
