### ISSUE TITLE
oereb_waldgrenzen Aussage und artcode "in Bauzone" und "ausserhalb Bauzone" 

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#114]
Der Bund hat bemängelt, dass die Aussage "in Bauzonen" und "ausserhalb Bauzonen" heissen muss. Und nicht wie momentan "Waldgrenzen"
![Bauzone](https://user-images.githubusercontent.com/3929984/84144489-9ca31980-aa58-11ea-97cb-8f50aa1b866b.jpg)

Der GRETL-Job muss angepasst werden.  In der Tabelle awjf_statische_waldgrenze"."geobasisdaten_typ" attribut "art" steckt das wissen.  

Nutzungsplanung_in_Bauzonen = in Bauzonen
Nutzungsplanung_ausserhalb_Bauzonen = ausserhalb Bauzonen
Einzelfeststellung =  ausserhalb Bauzonen
anderes_Verfahren = ausserhalb Bauzonen

Die Aussage ist demnach entweder "in Bauzonen" oder "ausserhalb Bauzonen"

Aussage und artcode bei transferstruktur_eigentumsbeschraenkung muss angepasst werden. 

Der WMS muss Andi dann am Schluss auch anpassen

**Comment by barpasen** [comment]
Bitte Branch oereb_waldgrenzen_b2 testen

**Comment by Luescher** [comment]
es sollte "in Bauzonen" heissen. "in" fehlt

**Comment by Luescher** [comment]
artcode:
- "in_Bauzonen" 
- "ausserhalb_Bauzonen"

**Comment by barpasen** [comment]
Aussage und artcode korrigiert

**Comment by Luescher** [comment]
passt soweit. Merci

**Comment by schmandr** [comment]
Gelöst mit #117
