### ISSUE TITLE
[oereb_grundwasserschutz] Typen Sm und Sh geben Fehler

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#146]
Siehe https://gretl.so.ch/blue/organizations/jenkins/oereb_gewaesserschutz/detail/oereb_gewaesserschutz/5/pipeline

Aussage muss erweitert werden mit Sh und Sm

CASE
	    WHEN gwszone.typ = 'S1'
	        THEN 'Grundwasserschutzzone S1'
	    WHEN gwszone.typ = 'S2'
		THEN 'Grundwasserschutzzone S2'
	    WHEN gwszone.typ = 'S3'
		THEN 'Grundwasserschutzzone S3'
	    **WHEN gwszone.typ = 'Sh'
		THEN 'Grundwasserschutzzone Sh'
             WHEN gwszone.typ = 'Sm'
		THEN 'Grundwasserschutzzone Sm'**
	END AS aussage_de,

**Comment by Luescher** [comment]
S3Zu gibt es auch noch und evtl.  S_kantonaleArt (im kant. Modell S3_Plus) diese wird noch abgeklärt.

**Comment by Luescher** [comment]
Bitte ergänzen...
WHEN gwszone.typ = 'S3Zu'
THEN 'Grundwasserschutzzone S3Zu'
WHEN gwszone.typ = 'S3_Plus'
THEN 'Grundwasserschutzzone S3_Plus'


Artcode ....

CASE
WHEN gwszone.typ  = S3_Plus
THEN 'S_kantonaleArt'
ELSE gwszone.typ 
END AS artcode


Nur bei S3_Plus soll der Wert bei artcode anders sein als der gwszone.typ

**Comment by barpasen** [comment]
SchutzzoneTyp :  'S3_Plus' gibt es gemäss Modell nicht, sondern 'S_kantonaleArt'.
Müsste es so sein?
WHEN gwszone.typ = 'S3Zu'
THEN 'Grundwasserschutzzone S3Zu'
WHEN gwszone.typ = 'S_kantonaleArt'
THEN 'Grundwasserschutzzone S_kantonaleArt'

Artcode ....

CASE
WHEN gwszone.typ = 'S_kantonaleArt'
THEN 'S3_Plus'
ELSE gwszone.typ
END AS artcode

**Comment by Luescher** [comment]
Edit-DB: Modell "PlanerischerGewaesserschutz_LV95_V1_1" mit
  SchutzzoneTyp = (
        S1,
        S2,
        S3,
        S3Zu,
        S_kantonaleArt,
        Sh,
        Sm

Pub-DB: Modell "SO_AfU_Gewaesserschutz_Publikation_20200115" mit
ZoneUndAreal_Typ = (
        S1,
        S2,
        S3,
        S3_Plus,
        Areal,
        Sm,
        Sh,
        S3Zu

Wie ist das Mapping von S3_Plus? Da gibt es in der Edit-DB in der Tabelle "afu_gewaesserschutz"."gwszonen_schutzzonetyp" "S3_Plus" nicht? Werden diese Zonen in der Edit-DB als  "S_kantonaleArt" erfasst?

**Comment by Luescher** [comment]
Oliver:
Ja S_kantonaleArt, da auf der Edit-DB das Bundesmodell vorliegt. Da bis auf weiteres der einzige kantonale typ, muss beim Fitern auch nicht's Weiteres ausser S_ kantonaleArt berücksichtigt werden.

**Comment by Luescher** [comment]
Braucht demnach kein "CASE" bei Artcode ....
 Artcode=gwszone.typ

**Comment by Luescher** [comment]
Anpassungen i.O. WMS ausgerollt auf Prod.
