### ISSUE TITLE
"LegendeEintrag" im Transferfile fehlen bei oereb_einzelschutz_geotop und oereb_einzelschutz_naturreservat

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#148]

**Comment by barpasen** [comment]
Wir müssen uns beim artcode einigen auf Einzahl oder Plural, oder ich passe es einfach an den WMS an.
aktuell Datenumbau
'geschuetztes_Kulturdenkmal' AS artcode
'geotope' AS artcode
'naturschutzgebiete' AS artcode

aktuell WMS
artcode =  'geschuetztes_Kulturdenkmal'
artcode =  'geotope'
artcode =  'naturschutzgebiet'

**Comment by andreasneumann** [comment]
@barpasen siehe https://github.com/sogis/oereb-wms/issues/32
Der WMS wird auf Plural wechseln bei "naturschutzgebiete"
