### ISSUE TITLE
Datenumbau Naturreservate neue auch ins Subthema "ch.SO.NutzungsplanungUeberlagernd"  

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-gretljobs#153]
Alle Naturreservate (erlassen mit Einzelschutz oder per Nutzungsplanung) werden zukünftig im Modell http://geo.so.ch/models/ARP/SO_ARP_Naturreservate_20200609.ili (Edit-Schema: arp_naturreservate) nachgeführt. 
Neu werden die Naturreservate nur noch per Nutzungsplanungsverfahren erlassen. 

Der GRTEL-Job "oereb_einzelschutz_naturreservat" muss deshalb angepasst werden. Die Naturreservate werden neu auch im Subthema "ch.SO.NutzungsplanungUeberlagernd" publiziert. Ob die Naturreservate unter weiteres Thema "ch.SO.Einzelschutz" oder als Subthema "ch.SO.NutzungsplanungUeberlagernd" im ÖREB-Kataster publiziert wird, hängt vom Attribut "reservat.einzelschutz" ab.

Das heisst der GRTEL-Job "oereb_einzelschutz_naturreservat" beinhaltet zukünftig den Datenumbau für das weitere Thema "ch.SO.Einzelschutz" und für das Subthema "ch.SO.NutzungsplanungUeberlagernd". Der GRETL-Job kann deshalb unbenannt werden in **"oereb_naturreservat"**.

Ich glaube folgende Änderungen müssen im "insert_oereb_einzelschutz_naturreservat_tables.sql" vorgenommen werden. Aber bitte gut prüfen... Das mit Artcode und Liste weiss ich nicht... muss man das auch noch ergänzen.
> 
>             CASE 
> 		    WHEN reservat.einzelschutz IS TRUE
> 		        THEN 'WeiteresThema'
>             ELSE 'Nutzungsplanung'		
> 		END AS thema,
> 		CASE 
> 		    WHEN reservat.einzelschutz IS TRUE
> 		        THEN 'ch.SO.Einzelschutz'
>             ELSE Null		
> 		END AS weiteresthema,
> 		CASE 
> 		    WHEN reservat.einzelschutz IS TRUE
> 		        THEN Null
>             ELSE 'ch.SO.NutzungsplanungUeberlagernd'		
> 		END AS subthema
> ......
> 

Entfernen.. bei  WHERE (Zeile 55/56)
`    AND
        reservat.einzelschutz IS TRUE`

GRETL-Job "oereb_nutzungsplanung" muss nicht angepasst werden die Typ "N522_Naturreservat_inkl_Geotope" wurde nie publiziert im ÖREB-Kataster.

Bitte koordinieren mit Anpassung im WMS. Bei nutzungsplanung_ueberlagernd_flaeche.qml muss eine Anpassung gemacht werden. Darstellung ist identisch zum Einzelschutz.
Wahrscheinlich 
 filter="artcode =  'naturschutzgebiete'"  label="Naturschutzgebiete"

**Comment by barpasen** [comment]
@andreasneumann Der Gretl-Job lief in der Testumgebung durch, aus meiner Sicht fehlt nur noch das Symbol für artcode = '5220', thema = 'Nutzungsplanung', subthema = 'ch.SO.NutzungsplanungUeberlagernd'

**Comment by barpasen** [comment]
@andreasneumann Kannst du das QML "nutzungsplanung_ueberlagernd_flaeche.qml" noch anpassen (siehe oben)
 artcode = '5220', thema = 'Nutzungsplanung', subthema = 'ch.SO.NutzungsplanungUeberlagernd' Label='Naturschutzgebiete'

**Comment by andreasneumann** [comment]
Wurde mit https://github.com/sogis/oereb-wms/commit/ab05b51c8804d80356d153ed24a91944e8934791 umgesetzt.

Mit https://github.com/sogis/oereb-wms/commit/e1721f88c4580b4e2f227d1588b07132f37657e7 wurde zudem das CI endlich nach Github migriert und der WMS damit in der Testumgebung ausgerollt.
