### ISSUE TITLE
[oereb_annex] Der Job führt die Downloads zweimal aus

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#18]
Der Job oereb_annex führt alle Downloads zweimal aus, sozusagen einmal für stage, einmal für live.

Er müsste irgendwie zuerst alle Downloads und danach erst die each-Schleife ausführen. Ich habe es bei einem anderen Job so gelöst: https://github.com/sogis/oereb-gretljobs/blob/master/oereb_gesetze/build.gradle

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-gretljobs/commit/c755b23ca0e4ecc9489c92155cf1423100f39742
