### ISSUE TITLE
Jenkinsfiles sollen gretl statt gradle aufrufen (?)

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#20]
Die Jenkinsfiles sollen `gretl` statt `gradle --init-script /home/gradle/init.gradle` aufrufen. Bin mir da aber noch nicht 100% sicher.

Plus sicherstellen, dass dasselbe in den start-gretl.sh-Skripten aufgerufen wird.

**Comment by schmandr** [comment]
Bestandesaufnahme:

`gretl` macht
```
gradle "${run_parameter[@]}" \
       --init-script /home/gradle/init.gradle \
       --stacktrace \
       --no-daemon \
```
(siehe https://github.com/sogis/gretl/blob/86bb40e23bdc3ea79b4ec09896eeb3f4c80725b9/runtimeImage/gretl/gretl#L9-L12)

In den Jenkinsfiles kommt `gradle --init-script /home/gradle/init.gradle` zum Einsatz. Hier fehlt also `--stacktrace` und `--no-daemon`.

In den start-gretl.sh-Skripten kommt `gretl` um Einsatz.

**Comment by edigonzales** [comment]
Stand?
