### ISSUE TITLE
[oereb_av] braucht das Download-Plugin nicht

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#21]
https://github.com/sogis/oereb-gretljobs/blob/2bb05eb27bc5ac528b468e48cbaf8f0f1841a7ab/oereb_av/build.gradle#L7

Diese Zeile und auch die Zeile `import de.undercouch.gradle.tasks.download.Download` oberhalb kann entfernt werden.

Auch `import java.nio.file.Paths` braucht es nicht.

Dasselbe gilt für _oereb_gbkreise_. Und für _oereb_plzo_.

**Comment by andreasneumann** [comment]
fixed in https://github.com/sogis/oereb-gretljobs/commit/5365326f670c1c7c9a562090bab2462a371f131f
