### ISSUE TITLE
[oereb_bundesdaten_gesetze] getAt(0) braucht es nicht

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#22]
https://github.com/sogis/oereb-gretljobs/blob/2bb05eb27bc5ac528b468e48cbaf8f0f1841a7ab/oereb_bundesdaten_gesetze/build.gradle#L36

Ebenfalls einfacher lösen: Die Initialisierung des Arrays

**Comment by edigonzales** [comment]
Andere Umbau-Jobs bitte auch gleich strählen.

**Comment by schmandr** [comment]
Fixed mit #78.

Die anderen Umbau-Jobs sind i.O.
