### ISSUE TITLE
Doku (Readme) schreiben

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#23]
Gleichzeitig überlegen, ob der Ordner oereb_nutzungsplanung/dev nicht eine Ebene höher platziert werden soll, damit er irgendwie allgemein für alle derartigen Jobs benutzt werden kann.

Idee: Mit docker-compose up startet ja bereits jetzt auch ein GRETL. Dieses könnte die Gesetze etc. gleich in die Edit-DB importieren, und auch alle Erfassungsschemen inkl. Daten anlegen. Ggf. noch per Env-Variable steuern, ob alle oder nur bestimmte Erfassungsdaten importiert werden sollen.

**Comment by edigonzales** [comment]
Fehlt noch was?

**Comment by schmandr** [comment]
Das Wichtigste ist da. Insbesondere ist beschrieben, wie man docker-compose einsetzt, um die DBs für die Entwicklung anzulegen und zu befüllen.
