### ISSUE TITLE
[oereb_nutzungsplanung] Expose WMS-Search-Replace-Parameter

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-gretljobs#44]
Es gibt neu einen Search/Replace-Task, der im XTF den Host-Namen (andere Teile wären auch möglich) des WMS-Servers austauscht. Den Parameter sollte man noch exposen, damit man das auch steuern kann, ohne build.gradle anzupassen.

Wie machen wir das am besten?

Siehe https://github.com/sogis/oereb-gretljobs/commit/58c103378902d4f3a60b9dc8d7a0699a47c201df

**Comment by schmandr** [comment]
Mein Vorschlag: Ich setze in GRETL-Jenkins eine Umgebungsvariable, so dass man im GRETL-Job (build.gradle) über die Variable `geoservicesHostName` (Vorschlag) je nach Umgebung _geo-t.so.ch_, _geo-i.so.ch_ oder _geo.so.ch_ erhält.

**Comment by schmandr** [comment]
Die Zeile https://github.com/sogis/oereb-gretljobs/blob/58c103378902d4f3a60b9dc8d7a0699a47c201df/oereb_nutzungsplanung/build.gradle#L20 muss man dann wohl ebenfalls so behandeln.

**Comment by schmandr** [comment]
OK, ist so bereit (https://github.com/sogis/oereb-gretljobs/commit/563f244245a6bd2b0fea97dd9a645bd84013cc37): Mit der Variable `geoservicesHostName` kann man auf den Hostnamen des WMS etc. zugreifen. Es liefert je nach Umgebung also _geo-t.so.ch_, _geo-i.so.ch_ oder _geo.so.ch_ erhält.

**Comment by schmandr** [comment]
@edigonzales Bittte mach die Änderungen, die du hier noch machen musst, dann gleichzeitig auch beim Job _oereb_grundwasserschutz_. Danke.
