### ISSUE TITLE
refreshOerebWMSTablesStage schlägt fehl

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#52]
Der Schritt `refreshOerebWMSTablesStage` schlägt fehl, weil da noch `CREATE INDEX` statements drin sind. Braucht es diese hier wirklich noch?

**Comment by andreasneumann** [comment]
Nein - die braucht es natürlich nicht. Sorry. Wird gefixt.

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-gretljobs/commit/9fd849e1ecd07b5cb90c17bfabafca85ebfd6c6c
