### ISSUE TITLE
[oereb_av] Fehler ab der zweiten Ausführung auf der Produktivumgebung

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#54]
Aber der zweiten Ausführung des Jobs oereb_av schlägt er mit folgendem Fehler fehl:
```
Exception in creating / invoking SqlExecutorStep.
org.postgresql.util.PSQLException: ERROR: update or delete on table "dm01vch24lv95dliegenschaften_grundstueck" violates foreign key constraint "dm01vch24lv95ftn_slbstrcht_selbstrecht_von_fkey" on table "dm01vch24lv95dliegenschaften_selbstrecht"
  Detail: Key (t_id)=(71496004) is still referenced from table "dm01vch24lv95dliegenschaften_selbstrecht".
```
Gesamtes Log: https://gretl.so.ch/blue/organizations/jenkins/oereb_av/detail/oereb_av/3/pipeline

Liegt wohl irgendwie an der Reihenfolge, wie die Daten übertragen/gelöscht werden. Interessanterweise war das in der Testumgebung soweit ich mich erinnern kann ein einziges Mal ebenfalls ein Problem, sonst aber nie.

**Comment by andreasneumann** [comment]
Das "Löschen" der Selbstrechte fehlte im "Delete-Job". Vermutlich behebt 7c6f12b93dfdef035c86cb807374f0f1274ee205 das Problem?

**Comment by andreasneumann** [comment]
fixed with 7c6f12b93dfdef035c86cb807374f0f1274ee205
