### ISSUE TITLE
Job-Trigger-Einstellungen

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-gretljobs#79]
Sind alle Triggers in den verschiedenen Jobs so eingestellt, wie man sich das vorstellt? Es gibt ja on-demand und daily Jobs.

**Comment by schmandr** [comment]
Gegenwärtig werden täglich automatisch ausgeführt:
* oereb_annex
* oereb_av
* oereb_gbkreise
* oereb_plzo

Dies entspricht dem, was @edigonzales und @schmandr ca. letzten Sommer am Whiteboard erarbeitet haben.

Muss noch etwas Weiteres? Kandidat wäre
* oereb_bundesdaten

Folgende müssen sicher nicht, weil es wegen den Abhängigkeiten gar nicht funktionieren würde:
* oereb_bundesgesetze
* oereb_kantonale_gesetze

Foldende sind explizite on demand jobs:
* oereb_belastete_standorte
* oereb_grundwasserschutz
* oereb_nutzungsplanung

Nicht ganz klar ist mir
* oereb_bundescodelisten

Das sind dann alle Jobs, insgesamt sind es 11.

**Comment by edigonzales** [comment]
- `oereb_bundesdaten` müssen täglich sein.
- `oereb_bundescodelisten ` on-demand. Verhält sich analog Gesetze.

**Comment by schmandr** [comment]
Noch die definitive Übersicht:

### Werden täglich automatisch ausgeführt:
* oereb_annex
* oereb_av
* oereb_bundesdaten
* oereb_gbkreise
* oereb_plzo

### Werden nicht täglich ausgeführt, weil es wegen Abhängigkeiten (Beziehungen) gar nicht funktionieren würde:
* oereb_bundesgesetze
* oereb_kantonale_gesetze
* oereb_bundescodelisten

### Explizite on demand jobs:
* oereb_belastete_standorte
* oereb_grundwasserschutz
* oereb_nutzungsplanung
