### ISSUE TITLE
Job-Ausführungen der on demand jobs unbegrenzt aufbewahren?

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#85]
Standardmässig werden bei uns in Jenkins 15 Job-Ausführungen aufbewahrt. Mit der 16. Ausführung wird also die erste gelöscht. Ist das ausreichend für die _on demand jobs_, oder sollen diese unbegrenzt aufbewahrt werden, damit die History (wer hat wann ausgeführt?, was für ein .xtf wurde produziert?) bis ganz zum Anfang ersichtlich ist?

**Comment by Luescher** [comment]
Bitte unbegrenzt aufbewahren vorallem die xtf sind wichtig

**Comment by schmandr** [comment]
Ist erledigt.
