### ISSUE TITLE
[oereb_av] ST_CurveToLine entfernen

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-gretljobs#89]
Die Funktion kann in den SQL-Queries entfernt werden, da die Inputgeometrien keine Kreisbogen mehr beinhalten. Eventuell aufpassen, ob Folge-Funktionen auch entfernt werden sollten.

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-gretljobs/commit/2c90455d12f20a4debba7413ce811f62e3404c36
