### ISSUE TITLE
Belastete Standorte: Das Attribut "verweiswms" verweist immer auf geo.so.ch/...

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-gretljobs#96]
Das Attribut "verweiswms" verweist immer auf geo.so.ch/..., statt dass es abhängig von der Umgebung auf geo-t.so.ch/... und geo-i.so.ch7... zeigt. Ist das ein Problem, oder können wir es lassen?

Bei den Jobs, bei denen wir den Datenumbau selbst machen, ersetzen wir das jeweils je nach Umgebung, aber bei "Belastete Standorte", wo wir die fertigen Daten erhalten, machen wir es nicht.

**Comment by edigonzales** [comment]
Wäre nicht am saubersten, wenn die Daten aus der entsprechenden Umgebung des Systems kämen:
https://altlast4web.verw.rootso.org/interlis_exports/oereb/data.zip 
-> altlast4web-t gibt es glaub.

Wenn wir es einfach einen GRET-Task zwischenschalten würden, wären es ja immer die gleichen Daten.

@schmandr @Luescher was meint ihr?

**Comment by schmandr** [comment]
Habe das kurz getestet, und über https://altlast4web-t.verw.rootso.org/interlis_exports/oereb/data.zip steht dann auch tatsächlich geo-t.so.ch/... drin.

altlast4web-i gibt es aber leider nicht; hier würde das nichts nützen.

Ich bin aber nicht ganz überzeugt, ob Zugreifen auf altlast4web-t gaz sauber ist: Andrea und ich haben es uns schon mal überlegt, in GRETL Test auf altlast4web-t zu gehen, sind aber zum Schluss gekommen: Das AfU/sein Lieferant muss ja hier eben Tests machen können, ohne dass wir darüber informiert sind. Das Testsystem kann also auch mal für gewisse Zeit nicht funktionieren, oder was auch immer. Und dann würde der GRETL-Job auh bei uns nicht mehr funktionieren.
Zudem greifen wir auch bei anderen Fremdsystemen in allen GRETL-Umgebungen auf die produktiven Fremdsysteme zu (z.B. KASO-DB).

Vielleicht ist es ja auch fast gar kein Problem. Die Daten der Test- und Integrationssysteme geben wir ja nicht ab. Der einzige Nachteil wäre dann noch, dass im Web GIS Client Test und Integration immer der produktive OEREB-WMS angezapft wird.

**Comment by Luescher** [comment]
Implizit wäre es natürlich schon sinnvoll altlast4web-t wird bei uns in die Testumgebung importiert. Falls Geops beim Export Änderungen machen, möchte man das ja auch testen. Sonst können wir das gar nicht testen.
Das mit der Integrationsumgebung ist einfach blöde. Weil altlast4web keine hat. Aber das haben wir doch auch z.B. beim Jasper Report oder da zeigen wir bei der Integration dann auf Produktiv… Weil Integration und Produktiv näher sind… Dasselbe auch z.B. bei Link zum intercapi im Web GIS Client

**Comment by edigonzales** [comment]
Handlungsbedarf? Sonst schliessen. @Luescher

**Comment by Luescher** [comment]
Wir lassen es momentan so wie es ist. Beim Import KBS  MGDM oder so ... kann das nochmals überlegt werden.
